[DEFAULT]
ENVIRONMENT = QAT
ACTIVE_FABRIC_LAYER = GOLD

[DATABASE]
DB_TYPE = SQLITE
DB_HOST = localhost
DB_PORT = 5432
DB_NAME = etl_test.db
DB_USER = test_user
DB_PASSWORD = test_password
DB_PATH = etl_test.db
SNOWFLAKE_ACCOUNT = your_account
SNOWFLAKE_USER = your_user
SNOWFLAKE_PASSWORD = your_password
SNOWFLAKE_WAREHOUSE = your_warehouse
SNOWFLAKE_DATABASE = your_database
SNOWFLAKE_SCHEMA = your_schema
ENGINE = sqlite
HOST = localhost
PORT = 5432
USERNAME = 
PASSWORD = 

[FABRIC]
FABRIC_TENANT_ID = a4b89f32-a57c-41e7-a690-85a9b7ea178b
FABRIC_AUTH_METHOD = Interactive

[AX_SOURCE]
AX_SERVER = ax-sqlpt01_basic
AX_PORT = 1433
AX_DATABASE = AX12_SIPT03
AX_AUTH_METHOD = Windows

[FABRIC_BRONZE]
DEV_BRONZE_LAKEHOUSE_NAME = LH_AX_CANADA
DEV_BRONZE_SQL_ENDPOINT = gkp3rjd4uxtudjuqqwu3p2qxrm-svm2ng66js2unkbavzr6avhrim.datawarehouse.fabric.microsoft.com
QAT_BRONZE_LAKEHOUSE_NAME = 
QAT_BRONZE_SQL_ENDPOINT = 
PROD_BRONZE_LAKEHOUSE_NAME = 
PROD_BRONZE_SQL_ENDPOINT = 
BRONZE_LAKEHOUSE_NAME = 
BRONZE_SQL_ENDPOINT = 

[FABRIC_SILVER]
DEV_SILVER_LAKEHOUSE_NAME = LH_Finance
DEV_SILVER_SQL_ENDPOINT = gkp3rjd4uxtudjuqqwu3p2qxrm-3v36dwrf2xlevbpqsbhfyvj2cu.datawarehouse.fabric.microsoft.com
QAT_SILVER_LAKEHOUSE_NAME = 
QAT_SILVER_SQL_ENDPOINT = 
PROD_SILVER_LAKEHOUSE_NAME = 
PROD_SILVER_SQL_ENDPOINT = 
SILVER_LAKEHOUSE_NAME = 
SILVER_SQL_ENDPOINT = 

[FABRIC_GOLD]
DEV_GOLD_LAKEHOUSE_NAME = enterprise_dwh
DEV_GOLD_SQL_ENDPOINT = gkp3rjd4uxtudjuqqwu3p2qxrm-ftoxi2fql3auhlczjcsdpaf5pa.datawarehouse.fabric.microsoft.com
QAT_GOLD_LAKEHOUSE_NAME = qat
QAT_GOLD_SQL_ENDPOINT = 
PROD_GOLD_LAKEHOUSE_NAME = enterprise_dwhgg
PROD_GOLD_SQL_ENDPOINT = 
GOLD_LAKEHOUSE_NAME = qat
GOLD_SQL_ENDPOINT = 

[INTEGRATION]
SOURCE_DB = test_audit_src_test.db
TARGET_DB = test_audit_tgt_test.db
KEY_COLUMN = id
RECONCILIATION_TYPE = data_diff

[API]
API_BASE_URL = https://fakestoreapi.com
API_TIMEOUT = 30
SSL_VERIFY = False

[TESTING]
CSV_FILE = test_cases.csv
SQL_DIR = sql
REPORT_DIR = reports
ENABLE_PARALLEL = False
MAX_WORKERS = 4

[REPORTING]
ALLURE_RESULTS = reports/allure-results
XML_RESULTS = reports/xml-results
GENERATE_XML = True
GENERATE_HTML = True

